### ISSUE TITLE
Proučavanje algoritma: XGBoost

### ISSUE THREAD

**Issue by CvetkovskiIvor** [CvetkovskiIvor/psj-projekt#3]
https://www.geeksforgeeks.org/xgboost-for-regression/#:~:text=The%20results%20of%20the%20regression,squared%2Derror%20(MSE).

**Comment by DaveXo9** [comment]
https://www.kaggle.com/code/shreayan98c/boston-house-price-prediction#Evaluation-and-comparision-of-all-the-models
